version: 1.2

workflows:
  - name: scgpt-embeddings-for-spatialfusion
    subclass: WDL
    primaryDescriptorPath: /workflows/unimodal-embeddings/wdl/scgpt_embeddings_for_spatialfusion.wdl
    readMePath: /workflows/unimodal-embeddings/wdl/README.md
    testParameterFiles:
      - /workflows/unimodal-embeddings/wdl/scgpt_embeddings_for_spatialfusion_inputs.json
  - name: uni-embeddings-for-spatialfusion
    subclass: WDL
    primaryDescriptorPath: /workflows/unimodal-embeddings/wdl/uni_embeddings_for_spatialfusion.wdl
    readMePath: /workflows/unimodal-embeddings/wdl/README.md
    testParameterFiles:
      - /workflows/unimodal-embeddings/wdl/uni_embeddings_for_spatialfusion_inputs.json
  - name: virchow2-embeddings-for-spatialfusion
    subclass: WDL
    primaryDescriptorPath: /workflows/unimodal-embeddings/wdl/virchow2_embeddings_for_spatialfusion.wdl
    readMePath: /workflows/unimodal-embeddings/wdl/README.md
    testParameterFiles:
      - /workflows/unimodal-embeddings/wdl/virchow2_embeddings_for_spatialfusion_inputs.json
  - name: nicheformer-embeddings-for-spatialfusion
    subclass: WDL
    primaryDescriptorPath: /workflows/unimodal-embeddings/wdl/nicheformer_embeddings_for_spatialfusion.wdl
    readMePath: /workflows/unimodal-embeddings/wdl/README.md
    testParameterFiles:
      - /workflows/unimodal-embeddings/wdl/nicheformer_embeddings_for_spatialfusion_inputs.json
