site_name: SpatialFusion Documentation
repo_url: https://github.com/uhlerlab/spatialfusion

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["spatialfusion"]
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true

nav:
  - Home: index.md
  - Prepare inputs: unimodal-embeddings.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Concepts: concepts.md
  - Data: data.md
  - Tutorials: tutorials.md
  - API Reference: 
    - Overview: api/index.md
    - spatialfusion.embed.embed: api/embed.md
    - spatialfusion.models.multi_ae: api/models_multi_ae.md
    - spatialfusion.models.gcn: api/models_gcn.md
    - spatialfusion.finetune.finetune: api/finetune.md
    - spatialfusion.utils.ae_utils: api/utils_ae.md
    - spatialfusion.utils.embed_gcn_utils: api/utils_embed_gcn.md
    - spatialfusion.utils.gcn_utils: api/utils_gcn.md
  - FAQ: faq.md
      
